/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ms.internet.message.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import com.ms.internet.message.service.persistence.MSMReceiverPK;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the MSMReceiver service. Represents a row in the &quot;MS_MSMReceiver&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.ms.internet.message.model.impl.MSMReceiverModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.ms.internet.message.model.impl.MSMReceiverImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a m s m receiver model instance should use the {@link MSMReceiver} interface instead.
 * </p>
 *
 * @author I Am Dung
 * @see MSMReceiver
 * @see com.ms.internet.message.model.impl.MSMReceiverImpl
 * @see com.ms.internet.message.model.impl.MSMReceiverModelImpl
 * @generated
 */
public interface MSMReceiverModel extends BaseModel<MSMReceiver> {
	/**
	 * Gets the primary key of this m s m receiver.
	 *
	 * @return the primary key of this m s m receiver
	 */
	public MSMReceiverPK getPrimaryKey();

	/**
	 * Sets the primary key of this m s m receiver
	 *
	 * @param pk the primary key of this m s m receiver
	 */
	public void setPrimaryKey(MSMReceiverPK pk);

	/**
	 * Gets the user id of this m s m receiver.
	 *
	 * @return the user id of this m s m receiver
	 */
	public long getUserId();

	/**
	 * Sets the user id of this m s m receiver.
	 *
	 * @param userId the user id of this m s m receiver
	 */
	public void setUserId(long userId);

	/**
	 * Gets the user uuid of this m s m receiver.
	 *
	 * @return the user uuid of this m s m receiver
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this m s m receiver.
	 *
	 * @param userUuid the user uuid of this m s m receiver
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Gets the message id of this m s m receiver.
	 *
	 * @return the message id of this m s m receiver
	 */
	public long getMessageId();

	/**
	 * Sets the message id of this m s m receiver.
	 *
	 * @param messageId the message id of this m s m receiver
	 */
	public void setMessageId(long messageId);

	/**
	 * Gets the date recieved of this m s m receiver.
	 *
	 * @return the date recieved of this m s m receiver
	 */
	public Date getDateRecieved();

	/**
	 * Sets the date recieved of this m s m receiver.
	 *
	 * @param dateRecieved the date recieved of this m s m receiver
	 */
	public void setDateRecieved(Date dateRecieved);

	/**
	 * Gets the ms status of this m s m receiver.
	 *
	 * @return the ms status of this m s m receiver
	 */
	public boolean getMsStatus();

	/**
	 * Determines if this m s m receiver is ms status.
	 *
	 * @return <code>true</code> if this m s m receiver is ms status; <code>false</code> otherwise
	 */
	public boolean isMsStatus();

	/**
	 * Sets whether this {$entity.humanName} is ms status.
	 *
	 * @param msStatus the ms status of this m s m receiver
	 */
	public void setMsStatus(boolean msStatus);

	/**
	 * Gets a copy of this m s m receiver as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public MSMReceiver toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(MSMReceiver msmReceiver);

	public int hashCode();

	public String toString();

	public String toXmlString();
}