/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.tvd.thptty.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TYMessages service. Represents a row in the &quot;TY_TYMessages&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.tvd.thptty.model.impl.TYMessagesModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.tvd.thptty.model.impl.TYMessagesImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a t y messages model instance should use the {@link TYMessages} interface instead.
 * </p>
 *
 * @author Ta Van Dung
 * @see TYMessages
 * @see org.tvd.thptty.model.impl.TYMessagesImpl
 * @see org.tvd.thptty.model.impl.TYMessagesModelImpl
 * @generated
 */
public interface TYMessagesModel extends BaseModel<TYMessages> {
	/**
	 * Gets the primary key of this t y messages.
	 *
	 * @return the primary key of this t y messages
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this t y messages
	 *
	 * @param pk the primary key of this t y messages
	 */
	public void setPrimaryKey(long pk);

	/**
	 * Gets the message id of this t y messages.
	 *
	 * @return the message id of this t y messages
	 */
	public long getMessageId();

	/**
	 * Sets the message id of this t y messages.
	 *
	 * @param messageId the message id of this t y messages
	 */
	public void setMessageId(long messageId);

	/**
	 * Gets the company id of this t y messages.
	 *
	 * @return the company id of this t y messages
	 */
	public long getCompanyId();

	/**
	 * Sets the company id of this t y messages.
	 *
	 * @param companyId the company id of this t y messages
	 */
	public void setCompanyId(long companyId);

	/**
	 * Gets the group id of this t y messages.
	 *
	 * @return the group id of this t y messages
	 */
	public long getGroupId();

	/**
	 * Sets the group id of this t y messages.
	 *
	 * @param groupId the group id of this t y messages
	 */
	public void setGroupId(long groupId);

	/**
	 * Gets the action id of this t y messages.
	 *
	 * @return the action id of this t y messages
	 */
	public long getActionId();

	/**
	 * Sets the action id of this t y messages.
	 *
	 * @param actionId the action id of this t y messages
	 */
	public void setActionId(long actionId);

	/**
	 * Gets the user id of this t y messages.
	 *
	 * @return the user id of this t y messages
	 */
	public long getUserId();

	/**
	 * Sets the user id of this t y messages.
	 *
	 * @param userId the user id of this t y messages
	 */
	public void setUserId(long userId);

	/**
	 * Gets the user uuid of this t y messages.
	 *
	 * @return the user uuid of this t y messages
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this t y messages.
	 *
	 * @param userUuid the user uuid of this t y messages
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Gets the class id of this t y messages.
	 *
	 * @return the class id of this t y messages
	 */
	public long getClassId();

	/**
	 * Sets the class id of this t y messages.
	 *
	 * @param classId the class id of this t y messages
	 */
	public void setClassId(long classId);

	/**
	 * Gets the subject id of this t y messages.
	 *
	 * @return the subject id of this t y messages
	 */
	public long getSubjectId();

	/**
	 * Sets the subject id of this t y messages.
	 *
	 * @param subjectId the subject id of this t y messages
	 */
	public void setSubjectId(long subjectId);

	/**
	 * Gets the happen date of this t y messages.
	 *
	 * @return the happen date of this t y messages
	 */
	public Date getHappenDate();

	/**
	 * Sets the happen date of this t y messages.
	 *
	 * @param happenDate the happen date of this t y messages
	 */
	public void setHappenDate(Date happenDate);

	/**
	 * Gets a copy of this t y messages as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public TYMessages toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(TYMessages tyMessages);

	public int hashCode();

	public String toString();

	public String toXmlString();
}