/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.tvd.thptty.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import org.tvd.thptty.service.persistence.TYStudentConductPK;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TYStudentConduct service. Represents a row in the &quot;TY_TYStudentConduct&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.tvd.thptty.model.impl.TYStudentConductModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.tvd.thptty.model.impl.TYStudentConductImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a t y student conduct model instance should use the {@link TYStudentConduct} interface instead.
 * </p>
 *
 * @author Ta Van Dung
 * @see TYStudentConduct
 * @see org.tvd.thptty.model.impl.TYStudentConductImpl
 * @see org.tvd.thptty.model.impl.TYStudentConductModelImpl
 * @generated
 */
public interface TYStudentConductModel extends BaseModel<TYStudentConduct> {
	/**
	 * Gets the primary key of this t y student conduct.
	 *
	 * @return the primary key of this t y student conduct
	 */
	public TYStudentConductPK getPrimaryKey();

	/**
	 * Sets the primary key of this t y student conduct
	 *
	 * @param pk the primary key of this t y student conduct
	 */
	public void setPrimaryKey(TYStudentConductPK pk);

	/**
	 * Gets the courses of this t y student conduct.
	 *
	 * @return the courses of this t y student conduct
	 */
	public int getCourses();

	/**
	 * Sets the courses of this t y student conduct.
	 *
	 * @param courses the courses of this t y student conduct
	 */
	public void setCourses(int courses);

	/**
	 * Gets the semester of this t y student conduct.
	 *
	 * @return the semester of this t y student conduct
	 */
	public int getSemester();

	/**
	 * Sets the semester of this t y student conduct.
	 *
	 * @param semester the semester of this t y student conduct
	 */
	public void setSemester(int semester);

	/**
	 * Gets the student id of this t y student conduct.
	 *
	 * @return the student id of this t y student conduct
	 */
	public long getStudentId();

	/**
	 * Sets the student id of this t y student conduct.
	 *
	 * @param studentId the student id of this t y student conduct
	 */
	public void setStudentId(long studentId);

	/**
	 * Gets the conduct of this t y student conduct.
	 *
	 * @return the conduct of this t y student conduct
	 */
	public int getConduct();

	/**
	 * Sets the conduct of this t y student conduct.
	 *
	 * @param conduct the conduct of this t y student conduct
	 */
	public void setConduct(int conduct);

	/**
	 * Gets the modified date of this t y student conduct.
	 *
	 * @return the modified date of this t y student conduct
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this t y student conduct.
	 *
	 * @param modifiedDate the modified date of this t y student conduct
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Gets the user id of this t y student conduct.
	 *
	 * @return the user id of this t y student conduct
	 */
	public long getUserId();

	/**
	 * Sets the user id of this t y student conduct.
	 *
	 * @param userId the user id of this t y student conduct
	 */
	public void setUserId(long userId);

	/**
	 * Gets the user uuid of this t y student conduct.
	 *
	 * @return the user uuid of this t y student conduct
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this t y student conduct.
	 *
	 * @param userUuid the user uuid of this t y student conduct
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Gets a copy of this t y student conduct as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public TYStudentConduct toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(TYStudentConduct tyStudentConduct);

	public int hashCode();

	public String toString();

	public String toXmlString();
}