/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.tvd.thptty.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import org.tvd.thptty.service.persistence.TYSubjectClassUserRolePK;

import java.io.Serializable;

/**
 * The base model interface for the TYSubjectClassUserRole service. Represents a row in the &quot;TY_TYSubjectClassUserRole&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.tvd.thptty.model.impl.TYSubjectClassUserRoleModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.tvd.thptty.model.impl.TYSubjectClassUserRoleImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a t y subject class user role model instance should use the {@link TYSubjectClassUserRole} interface instead.
 * </p>
 *
 * @author Ta Van Dung
 * @see TYSubjectClassUserRole
 * @see org.tvd.thptty.model.impl.TYSubjectClassUserRoleImpl
 * @see org.tvd.thptty.model.impl.TYSubjectClassUserRoleModelImpl
 * @generated
 */
public interface TYSubjectClassUserRoleModel extends BaseModel<TYSubjectClassUserRole> {
	/**
	 * Gets the primary key of this t y subject class user role.
	 *
	 * @return the primary key of this t y subject class user role
	 */
	public TYSubjectClassUserRolePK getPrimaryKey();

	/**
	 * Sets the primary key of this t y subject class user role
	 *
	 * @param pk the primary key of this t y subject class user role
	 */
	public void setPrimaryKey(TYSubjectClassUserRolePK pk);

	/**
	 * Gets the courses of this t y subject class user role.
	 *
	 * @return the courses of this t y subject class user role
	 */
	public int getCourses();

	/**
	 * Sets the courses of this t y subject class user role.
	 *
	 * @param courses the courses of this t y subject class user role
	 */
	public void setCourses(int courses);

	/**
	 * Gets the subject id of this t y subject class user role.
	 *
	 * @return the subject id of this t y subject class user role
	 */
	public long getSubjectId();

	/**
	 * Sets the subject id of this t y subject class user role.
	 *
	 * @param subjectId the subject id of this t y subject class user role
	 */
	public void setSubjectId(long subjectId);

	/**
	 * Gets the class id of this t y subject class user role.
	 *
	 * @return the class id of this t y subject class user role
	 */
	public long getClassId();

	/**
	 * Sets the class id of this t y subject class user role.
	 *
	 * @param classId the class id of this t y subject class user role
	 */
	public void setClassId(long classId);

	/**
	 * Gets the user id of this t y subject class user role.
	 *
	 * @return the user id of this t y subject class user role
	 */
	public long getUserId();

	/**
	 * Sets the user id of this t y subject class user role.
	 *
	 * @param userId the user id of this t y subject class user role
	 */
	public void setUserId(long userId);

	/**
	 * Gets the user uuid of this t y subject class user role.
	 *
	 * @return the user uuid of this t y subject class user role
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this t y subject class user role.
	 *
	 * @param userUuid the user uuid of this t y subject class user role
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Gets the role id of this t y subject class user role.
	 *
	 * @return the role id of this t y subject class user role
	 */
	public long getRoleId();

	/**
	 * Sets the role id of this t y subject class user role.
	 *
	 * @param roleId the role id of this t y subject class user role
	 */
	public void setRoleId(long roleId);

	/**
	 * Gets the status of this t y subject class user role.
	 *
	 * @return the status of this t y subject class user role
	 */
	public int getStatus();

	/**
	 * Sets the status of this t y subject class user role.
	 *
	 * @param status the status of this t y subject class user role
	 */
	public void setStatus(int status);

	/**
	 * Gets a copy of this t y subject class user role as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public TYSubjectClassUserRole toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(TYSubjectClassUserRole tySubjectClassUserRole);

	public int hashCode();

	public String toString();

	public String toXmlString();
}