/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.tvd.thptty.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.impl.BaseModelImpl;

import org.tvd.thptty.model.Semester;
import org.tvd.thptty.model.SemesterModel;
import org.tvd.thptty.service.persistence.SemesterPK;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

/**
 * The base model implementation for the Semester service. Represents a row in the &quot;TY_Semester&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.tvd.thptty.model.SemesterModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link SemesterImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. All methods that expect a semester model instance should use the {@link org.tvd.thptty.model.Semester} interface instead.
 * </p>
 *
 * @author Ta Van Dung
 * @see SemesterImpl
 * @see org.tvd.thptty.model.Semester
 * @see org.tvd.thptty.model.SemesterModel
 * @generated
 */
public class SemesterModelImpl extends BaseModelImpl<Semester>
	implements SemesterModel {
	public static final String TABLE_NAME = "TY_Semester";
	public static final Object[][] TABLE_COLUMNS = {
			{ "companyId", new Integer(Types.BIGINT) },
			{ "groupId", new Integer(Types.BIGINT) },
			{ "semesterId", new Integer(Types.INTEGER) },
			{ "status", new Integer(Types.INTEGER) }
		};
	public static final String TABLE_SQL_CREATE = "create table TY_Semester (companyId LONG not null,groupId LONG not null,semesterId INTEGER not null,status INTEGER,primary key (companyId, groupId, semesterId))";
	public static final String TABLE_SQL_DROP = "drop table TY_Semester";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.tvd.thptty.model.Semester"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.tvd.thptty.model.Semester"),
			true);
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.tvd.thptty.model.Semester"));

	public SemesterModelImpl() {
	}

	public SemesterPK getPrimaryKey() {
		return new SemesterPK(_companyId, _groupId, _semesterId);
	}

	public void setPrimaryKey(SemesterPK pk) {
		setCompanyId(pk.companyId);
		setGroupId(pk.groupId);
		setSemesterId(pk.semesterId);
	}

	public Serializable getPrimaryKeyObj() {
		return new SemesterPK(_companyId, _groupId, _semesterId);
	}

	public long getCompanyId() {
		return _companyId;
	}

	public void setCompanyId(long companyId) {
		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	public long getGroupId() {
		return _groupId;
	}

	public void setGroupId(long groupId) {
		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	public int getSemesterId() {
		return _semesterId;
	}

	public void setSemesterId(int semesterId) {
		_semesterId = semesterId;
	}

	public int getStatus() {
		return _status;
	}

	public void setStatus(int status) {
		if (!_setOriginalStatus) {
			_setOriginalStatus = true;

			_originalStatus = _status;
		}

		_status = status;
	}

	public int getOriginalStatus() {
		return _originalStatus;
	}

	public Semester toEscapedModel() {
		if (isEscapedModel()) {
			return (Semester)this;
		}
		else {
			return (Semester)Proxy.newProxyInstance(Semester.class.getClassLoader(),
				new Class[] { Semester.class }, new AutoEscapeBeanHandler(this));
		}
	}

	public Object clone() {
		SemesterImpl semesterImpl = new SemesterImpl();

		semesterImpl.setCompanyId(getCompanyId());

		SemesterModelImpl semesterModelImpl = semesterImpl;

		semesterModelImpl._originalCompanyId = semesterModelImpl._companyId;

		semesterModelImpl._setOriginalCompanyId = false;
		semesterImpl.setGroupId(getGroupId());

		semesterModelImpl._originalGroupId = semesterModelImpl._groupId;

		semesterModelImpl._setOriginalGroupId = false;
		semesterImpl.setSemesterId(getSemesterId());

		semesterImpl.setStatus(getStatus());

		semesterModelImpl._originalStatus = semesterModelImpl._status;

		semesterModelImpl._setOriginalStatus = false;

		return semesterImpl;
	}

	public int compareTo(Semester semester) {
		SemesterPK pk = semester.getPrimaryKey();

		return getPrimaryKey().compareTo(pk);
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		Semester semester = null;

		try {
			semester = (Semester)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		SemesterPK pk = semester.getPrimaryKey();

		if (getPrimaryKey().equals(pk)) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	public String toString() {
		StringBundler sb = new StringBundler(9);

		sb.append("{companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", semesterId=");
		sb.append(getSemesterId());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(16);

		sb.append("<model><model-name>");
		sb.append("org.tvd.thptty.model.Semester");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>semesterId</column-name><column-value><![CDATA[");
		sb.append(getSemesterId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private int _semesterId;
	private int _status;
	private int _originalStatus;
	private boolean _setOriginalStatus;
}