/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.tvd.thptty.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.util.PortalUtil;

import org.tvd.thptty.model.TYClassUserRole;
import org.tvd.thptty.model.TYClassUserRoleModel;
import org.tvd.thptty.service.persistence.TYClassUserRolePK;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

/**
 * The base model implementation for the TYClassUserRole service. Represents a row in the &quot;TY_TYClassUserRole&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.tvd.thptty.model.TYClassUserRoleModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TYClassUserRoleImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. All methods that expect a t y class user role model instance should use the {@link org.tvd.thptty.model.TYClassUserRole} interface instead.
 * </p>
 *
 * @author Ta Van Dung
 * @see TYClassUserRoleImpl
 * @see org.tvd.thptty.model.TYClassUserRole
 * @see org.tvd.thptty.model.TYClassUserRoleModel
 * @generated
 */
public class TYClassUserRoleModelImpl extends BaseModelImpl<TYClassUserRole>
	implements TYClassUserRoleModel {
	public static final String TABLE_NAME = "TY_TYClassUserRole";
	public static final Object[][] TABLE_COLUMNS = {
			{ "courses", new Integer(Types.INTEGER) },
			{ "classId", new Integer(Types.BIGINT) },
			{ "userId", new Integer(Types.BIGINT) },
			{ "roleId", new Integer(Types.BIGINT) },
			{ "status", new Integer(Types.INTEGER) }
		};
	public static final String TABLE_SQL_CREATE = "create table TY_TYClassUserRole (courses INTEGER not null,classId LONG not null,userId LONG not null,roleId LONG not null,status INTEGER,primary key (courses, classId, userId, roleId))";
	public static final String TABLE_SQL_DROP = "drop table TY_TYClassUserRole";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.tvd.thptty.model.TYClassUserRole"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.tvd.thptty.model.TYClassUserRole"),
			true);
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.tvd.thptty.model.TYClassUserRole"));

	public TYClassUserRoleModelImpl() {
	}

	public TYClassUserRolePK getPrimaryKey() {
		return new TYClassUserRolePK(_courses, _classId, _userId, _roleId);
	}

	public void setPrimaryKey(TYClassUserRolePK pk) {
		setCourses(pk.courses);
		setClassId(pk.classId);
		setUserId(pk.userId);
		setRoleId(pk.roleId);
	}

	public Serializable getPrimaryKeyObj() {
		return new TYClassUserRolePK(_courses, _classId, _userId, _roleId);
	}

	public int getCourses() {
		return _courses;
	}

	public void setCourses(int courses) {
		if (!_setOriginalCourses) {
			_setOriginalCourses = true;

			_originalCourses = _courses;
		}

		_courses = courses;
	}

	public int getOriginalCourses() {
		return _originalCourses;
	}

	public long getClassId() {
		return _classId;
	}

	public void setClassId(long classId) {
		if (!_setOriginalClassId) {
			_setOriginalClassId = true;

			_originalClassId = _classId;
		}

		_classId = classId;
	}

	public long getOriginalClassId() {
		return _originalClassId;
	}

	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public long getRoleId() {
		return _roleId;
	}

	public void setRoleId(long roleId) {
		if (!_setOriginalRoleId) {
			_setOriginalRoleId = true;

			_originalRoleId = _roleId;
		}

		_roleId = roleId;
	}

	public long getOriginalRoleId() {
		return _originalRoleId;
	}

	public int getStatus() {
		return _status;
	}

	public void setStatus(int status) {
		_status = status;
	}

	public TYClassUserRole toEscapedModel() {
		if (isEscapedModel()) {
			return (TYClassUserRole)this;
		}
		else {
			return (TYClassUserRole)Proxy.newProxyInstance(TYClassUserRole.class.getClassLoader(),
				new Class[] { TYClassUserRole.class },
				new AutoEscapeBeanHandler(this));
		}
	}

	public Object clone() {
		TYClassUserRoleImpl tyClassUserRoleImpl = new TYClassUserRoleImpl();

		tyClassUserRoleImpl.setCourses(getCourses());

		TYClassUserRoleModelImpl tyClassUserRoleModelImpl = tyClassUserRoleImpl;

		tyClassUserRoleModelImpl._originalCourses = tyClassUserRoleModelImpl._courses;

		tyClassUserRoleModelImpl._setOriginalCourses = false;
		tyClassUserRoleImpl.setClassId(getClassId());

		tyClassUserRoleModelImpl._originalClassId = tyClassUserRoleModelImpl._classId;

		tyClassUserRoleModelImpl._setOriginalClassId = false;
		tyClassUserRoleImpl.setUserId(getUserId());

		tyClassUserRoleImpl.setRoleId(getRoleId());

		tyClassUserRoleModelImpl._originalRoleId = tyClassUserRoleModelImpl._roleId;

		tyClassUserRoleModelImpl._setOriginalRoleId = false;
		tyClassUserRoleImpl.setStatus(getStatus());

		return tyClassUserRoleImpl;
	}

	public int compareTo(TYClassUserRole tyClassUserRole) {
		TYClassUserRolePK pk = tyClassUserRole.getPrimaryKey();

		return getPrimaryKey().compareTo(pk);
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		TYClassUserRole tyClassUserRole = null;

		try {
			tyClassUserRole = (TYClassUserRole)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		TYClassUserRolePK pk = tyClassUserRole.getPrimaryKey();

		if (getPrimaryKey().equals(pk)) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	public String toString() {
		StringBundler sb = new StringBundler(11);

		sb.append("{courses=");
		sb.append(getCourses());
		sb.append(", classId=");
		sb.append(getClassId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", roleId=");
		sb.append(getRoleId());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(19);

		sb.append("<model><model-name>");
		sb.append("org.tvd.thptty.model.TYClassUserRole");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>courses</column-name><column-value><![CDATA[");
		sb.append(getCourses());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>classId</column-name><column-value><![CDATA[");
		sb.append(getClassId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>roleId</column-name><column-value><![CDATA[");
		sb.append(getRoleId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private int _courses;
	private int _originalCourses;
	private boolean _setOriginalCourses;
	private long _classId;
	private long _originalClassId;
	private boolean _setOriginalClassId;
	private long _userId;
	private String _userUuid;
	private long _roleId;
	private long _originalRoleId;
	private boolean _setOriginalRoleId;
	private int _status;
}