/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.tvd.thptty.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.util.PortalUtil;

import org.tvd.thptty.model.TYStudentConduct;
import org.tvd.thptty.model.TYStudentConductModel;
import org.tvd.thptty.service.persistence.TYStudentConductPK;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

import java.util.Date;

/**
 * The base model implementation for the TYStudentConduct service. Represents a row in the &quot;TY_TYStudentConduct&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.tvd.thptty.model.TYStudentConductModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TYStudentConductImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. All methods that expect a t y student conduct model instance should use the {@link org.tvd.thptty.model.TYStudentConduct} interface instead.
 * </p>
 *
 * @author Ta Van Dung
 * @see TYStudentConductImpl
 * @see org.tvd.thptty.model.TYStudentConduct
 * @see org.tvd.thptty.model.TYStudentConductModel
 * @generated
 */
public class TYStudentConductModelImpl extends BaseModelImpl<TYStudentConduct>
	implements TYStudentConductModel {
	public static final String TABLE_NAME = "TY_TYStudentConduct";
	public static final Object[][] TABLE_COLUMNS = {
			{ "courses", new Integer(Types.INTEGER) },
			{ "semester", new Integer(Types.INTEGER) },
			{ "studentId", new Integer(Types.BIGINT) },
			{ "conduct", new Integer(Types.INTEGER) },
			{ "modifiedDate", new Integer(Types.TIMESTAMP) },
			{ "userId", new Integer(Types.BIGINT) }
		};
	public static final String TABLE_SQL_CREATE = "create table TY_TYStudentConduct (courses INTEGER not null,semester INTEGER not null,studentId LONG not null,conduct INTEGER,modifiedDate DATE null,userId LONG,primary key (courses, semester, studentId))";
	public static final String TABLE_SQL_DROP = "drop table TY_TYStudentConduct";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.tvd.thptty.model.TYStudentConduct"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.tvd.thptty.model.TYStudentConduct"),
			true);
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.tvd.thptty.model.TYStudentConduct"));

	public TYStudentConductModelImpl() {
	}

	public TYStudentConductPK getPrimaryKey() {
		return new TYStudentConductPK(_courses, _semester, _studentId);
	}

	public void setPrimaryKey(TYStudentConductPK pk) {
		setCourses(pk.courses);
		setSemester(pk.semester);
		setStudentId(pk.studentId);
	}

	public Serializable getPrimaryKeyObj() {
		return new TYStudentConductPK(_courses, _semester, _studentId);
	}

	public int getCourses() {
		return _courses;
	}

	public void setCourses(int courses) {
		if (!_setOriginalCourses) {
			_setOriginalCourses = true;

			_originalCourses = _courses;
		}

		_courses = courses;
	}

	public int getOriginalCourses() {
		return _originalCourses;
	}

	public int getSemester() {
		return _semester;
	}

	public void setSemester(int semester) {
		if (!_setOriginalSemester) {
			_setOriginalSemester = true;

			_originalSemester = _semester;
		}

		_semester = semester;
	}

	public int getOriginalSemester() {
		return _originalSemester;
	}

	public long getStudentId() {
		return _studentId;
	}

	public void setStudentId(long studentId) {
		if (!_setOriginalStudentId) {
			_setOriginalStudentId = true;

			_originalStudentId = _studentId;
		}

		_studentId = studentId;
	}

	public long getOriginalStudentId() {
		return _originalStudentId;
	}

	public int getConduct() {
		return _conduct;
	}

	public void setConduct(int conduct) {
		_conduct = conduct;
	}

	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public TYStudentConduct toEscapedModel() {
		if (isEscapedModel()) {
			return (TYStudentConduct)this;
		}
		else {
			return (TYStudentConduct)Proxy.newProxyInstance(TYStudentConduct.class.getClassLoader(),
				new Class[] { TYStudentConduct.class },
				new AutoEscapeBeanHandler(this));
		}
	}

	public Object clone() {
		TYStudentConductImpl tyStudentConductImpl = new TYStudentConductImpl();

		tyStudentConductImpl.setCourses(getCourses());

		TYStudentConductModelImpl tyStudentConductModelImpl = tyStudentConductImpl;

		tyStudentConductModelImpl._originalCourses = tyStudentConductModelImpl._courses;

		tyStudentConductModelImpl._setOriginalCourses = false;
		tyStudentConductImpl.setSemester(getSemester());

		tyStudentConductModelImpl._originalSemester = tyStudentConductModelImpl._semester;

		tyStudentConductModelImpl._setOriginalSemester = false;
		tyStudentConductImpl.setStudentId(getStudentId());

		tyStudentConductModelImpl._originalStudentId = tyStudentConductModelImpl._studentId;

		tyStudentConductModelImpl._setOriginalStudentId = false;
		tyStudentConductImpl.setConduct(getConduct());

		tyStudentConductImpl.setModifiedDate(getModifiedDate());

		tyStudentConductImpl.setUserId(getUserId());

		return tyStudentConductImpl;
	}

	public int compareTo(TYStudentConduct tyStudentConduct) {
		TYStudentConductPK pk = tyStudentConduct.getPrimaryKey();

		return getPrimaryKey().compareTo(pk);
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		TYStudentConduct tyStudentConduct = null;

		try {
			tyStudentConduct = (TYStudentConduct)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		TYStudentConductPK pk = tyStudentConduct.getPrimaryKey();

		if (getPrimaryKey().equals(pk)) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{courses=");
		sb.append(getCourses());
		sb.append(", semester=");
		sb.append(getSemester());
		sb.append(", studentId=");
		sb.append(getStudentId());
		sb.append(", conduct=");
		sb.append(getConduct());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append("org.tvd.thptty.model.TYStudentConduct");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>courses</column-name><column-value><![CDATA[");
		sb.append(getCourses());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>semester</column-name><column-value><![CDATA[");
		sb.append(getSemester());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>studentId</column-name><column-value><![CDATA[");
		sb.append(getStudentId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>conduct</column-name><column-value><![CDATA[");
		sb.append(getConduct());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private int _courses;
	private int _originalCourses;
	private boolean _setOriginalCourses;
	private int _semester;
	private int _originalSemester;
	private boolean _setOriginalSemester;
	private long _studentId;
	private long _originalStudentId;
	private boolean _setOriginalStudentId;
	private int _conduct;
	private Date _modifiedDate;
	private long _userId;
	private String _userUuid;
}