/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.tvd.thptty.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TYStudent service. Represents a row in the &quot;TY_TYStudent&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.tvd.thptty.model.impl.TYStudentModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.tvd.thptty.model.impl.TYStudentImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a t y student model instance should use the {@link TYStudent} interface instead.
 * </p>
 *
 * @author Ta Van Dung
 * @see TYStudent
 * @see org.tvd.thptty.model.impl.TYStudentImpl
 * @see org.tvd.thptty.model.impl.TYStudentModelImpl
 * @generated
 */
public interface TYStudentModel extends BaseModel<TYStudent> {
	/**
	 * Gets the primary key of this t y student.
	 *
	 * @return the primary key of this t y student
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this t y student
	 *
	 * @param pk the primary key of this t y student
	 */
	public void setPrimaryKey(long pk);

	/**
	 * Gets the student id of this t y student.
	 *
	 * @return the student id of this t y student
	 */
	public long getStudentId();

	/**
	 * Sets the student id of this t y student.
	 *
	 * @param studentId the student id of this t y student
	 */
	public void setStudentId(long studentId);

	/**
	 * Gets the company id of this t y student.
	 *
	 * @return the company id of this t y student
	 */
	public long getCompanyId();

	/**
	 * Sets the company id of this t y student.
	 *
	 * @param companyId the company id of this t y student
	 */
	public void setCompanyId(long companyId);

	/**
	 * Gets the group id of this t y student.
	 *
	 * @return the group id of this t y student
	 */
	public long getGroupId();

	/**
	 * Sets the group id of this t y student.
	 *
	 * @param groupId the group id of this t y student
	 */
	public void setGroupId(long groupId);

	/**
	 * Gets the user id of this t y student.
	 *
	 * @return the user id of this t y student
	 */
	public long getUserId();

	/**
	 * Sets the user id of this t y student.
	 *
	 * @param userId the user id of this t y student
	 */
	public void setUserId(long userId);

	/**
	 * Gets the user uuid of this t y student.
	 *
	 * @return the user uuid of this t y student
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this t y student.
	 *
	 * @param userUuid the user uuid of this t y student
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Gets the student last name of this t y student.
	 *
	 * @return the student last name of this t y student
	 */
	@AutoEscape
	public String getStudentLastName();

	/**
	 * Sets the student last name of this t y student.
	 *
	 * @param studentLastName the student last name of this t y student
	 */
	public void setStudentLastName(String studentLastName);

	/**
	 * Gets the student first name of this t y student.
	 *
	 * @return the student first name of this t y student
	 */
	@AutoEscape
	public String getStudentFirstName();

	/**
	 * Sets the student first name of this t y student.
	 *
	 * @param studentFirstName the student first name of this t y student
	 */
	public void setStudentFirstName(String studentFirstName);

	/**
	 * Gets the student group1 of this t y student.
	 *
	 * @return the student group1 of this t y student
	 */
	public int getStudentGroup1();

	/**
	 * Sets the student group1 of this t y student.
	 *
	 * @param studentGroup1 the student group1 of this t y student
	 */
	public void setStudentGroup1(int studentGroup1);

	/**
	 * Gets the student group2 of this t y student.
	 *
	 * @return the student group2 of this t y student
	 */
	public int getStudentGroup2();

	/**
	 * Sets the student group2 of this t y student.
	 *
	 * @param studentGroup2 the student group2 of this t y student
	 */
	public void setStudentGroup2(int studentGroup2);

	/**
	 * Gets the student group3 of this t y student.
	 *
	 * @return the student group3 of this t y student
	 */
	public int getStudentGroup3();

	/**
	 * Sets the student group3 of this t y student.
	 *
	 * @param studentGroup3 the student group3 of this t y student
	 */
	public void setStudentGroup3(int studentGroup3);

	/**
	 * Gets the male of this t y student.
	 *
	 * @return the male of this t y student
	 */
	public boolean getMale();

	/**
	 * Determines if this t y student is male.
	 *
	 * @return <code>true</code> if this t y student is male; <code>false</code> otherwise
	 */
	public boolean isMale();

	/**
	 * Sets whether this {$entity.humanName} is male.
	 *
	 * @param male the male of this t y student
	 */
	public void setMale(boolean male);

	/**
	 * Gets the birth day of this t y student.
	 *
	 * @return the birth day of this t y student
	 */
	public Date getBirthDay();

	/**
	 * Sets the birth day of this t y student.
	 *
	 * @param birthDay the birth day of this t y student
	 */
	public void setBirthDay(Date birthDay);

	/**
	 * Gets the email address of this t y student.
	 *
	 * @return the email address of this t y student
	 */
	@AutoEscape
	public String getEmailAddress();

	/**
	 * Sets the email address of this t y student.
	 *
	 * @param emailAddress the email address of this t y student
	 */
	public void setEmailAddress(String emailAddress);

	/**
	 * Gets the email password of this t y student.
	 *
	 * @return the email password of this t y student
	 */
	@AutoEscape
	public String getEmailPassword();

	/**
	 * Sets the email password of this t y student.
	 *
	 * @param emailPassword the email password of this t y student
	 */
	public void setEmailPassword(String emailPassword);

	/**
	 * Gets the address of this t y student.
	 *
	 * @return the address of this t y student
	 */
	@AutoEscape
	public String getAddress();

	/**
	 * Sets the address of this t y student.
	 *
	 * @param address the address of this t y student
	 */
	public void setAddress(String address);

	/**
	 * Gets the father name of this t y student.
	 *
	 * @return the father name of this t y student
	 */
	@AutoEscape
	public String getFatherName();

	/**
	 * Sets the father name of this t y student.
	 *
	 * @param fatherName the father name of this t y student
	 */
	public void setFatherName(String fatherName);

	/**
	 * Gets the father phone of this t y student.
	 *
	 * @return the father phone of this t y student
	 */
	@AutoEscape
	public String getFatherPhone();

	/**
	 * Sets the father phone of this t y student.
	 *
	 * @param fatherPhone the father phone of this t y student
	 */
	public void setFatherPhone(String fatherPhone);

	/**
	 * Gets the mother name of this t y student.
	 *
	 * @return the mother name of this t y student
	 */
	@AutoEscape
	public String getMotherName();

	/**
	 * Sets the mother name of this t y student.
	 *
	 * @param motherName the mother name of this t y student
	 */
	public void setMotherName(String motherName);

	/**
	 * Gets the mother phone of this t y student.
	 *
	 * @return the mother phone of this t y student
	 */
	@AutoEscape
	public String getMotherPhone();

	/**
	 * Sets the mother phone of this t y student.
	 *
	 * @param motherPhone the mother phone of this t y student
	 */
	public void setMotherPhone(String motherPhone);

	/**
	 * Gets the student code of this t y student.
	 *
	 * @return the student code of this t y student
	 */
	@AutoEscape
	public String getStudentCode();

	/**
	 * Sets the student code of this t y student.
	 *
	 * @param studentCode the student code of this t y student
	 */
	public void setStudentCode(String studentCode);

	/**
	 * Gets the login count of this t y student.
	 *
	 * @return the login count of this t y student
	 */
	public int getLoginCount();

	/**
	 * Sets the login count of this t y student.
	 *
	 * @param loginCount the login count of this t y student
	 */
	public void setLoginCount(int loginCount);

	/**
	 * Gets the date login of this t y student.
	 *
	 * @return the date login of this t y student
	 */
	public Date getDateLogin();

	/**
	 * Sets the date login of this t y student.
	 *
	 * @param dateLogin the date login of this t y student
	 */
	public void setDateLogin(Date dateLogin);

	/**
	 * Gets the password encrypt of this t y student.
	 *
	 * @return the password encrypt of this t y student
	 */
	public boolean getPasswordEncrypt();

	/**
	 * Determines if this t y student is password encrypt.
	 *
	 * @return <code>true</code> if this t y student is password encrypt; <code>false</code> otherwise
	 */
	public boolean isPasswordEncrypt();

	/**
	 * Sets whether this {$entity.humanName} is password encrypt.
	 *
	 * @param passwordEncrypt the password encrypt of this t y student
	 */
	public void setPasswordEncrypt(boolean passwordEncrypt);

	/**
	 * Gets the question of this t y student.
	 *
	 * @return the question of this t y student
	 */
	@AutoEscape
	public String getQuestion();

	/**
	 * Sets the question of this t y student.
	 *
	 * @param question the question of this t y student
	 */
	public void setQuestion(String question);

	/**
	 * Gets the answer of this t y student.
	 *
	 * @return the answer of this t y student
	 */
	@AutoEscape
	public String getAnswer();

	/**
	 * Sets the answer of this t y student.
	 *
	 * @param answer the answer of this t y student
	 */
	public void setAnswer(String answer);

	/**
	 * Gets the reg id of this t y student.
	 *
	 * @return the reg id of this t y student
	 */
	@AutoEscape
	public String getRegId();

	/**
	 * Sets the reg id of this t y student.
	 *
	 * @param regId the reg id of this t y student
	 */
	public void setRegId(String regId);

	/**
	 * Gets a copy of this t y student as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public TYStudent toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(TYStudent tyStudent);

	public int hashCode();

	public String toString();

	public String toXmlString();
}