/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.tvd.thptty.model;

import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import org.tvd.thptty.service.persistence.TYStudentPointPK;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TYStudentPoint service. Represents a row in the &quot;TY_TYStudentPoint&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.tvd.thptty.model.impl.TYStudentPointModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.tvd.thptty.model.impl.TYStudentPointImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a t y student point model instance should use the {@link TYStudentPoint} interface instead.
 * </p>
 *
 * @author Ta Van Dung
 * @see TYStudentPoint
 * @see org.tvd.thptty.model.impl.TYStudentPointImpl
 * @see org.tvd.thptty.model.impl.TYStudentPointModelImpl
 * @generated
 */
public interface TYStudentPointModel extends BaseModel<TYStudentPoint> {
	/**
	 * Gets the primary key of this t y student point.
	 *
	 * @return the primary key of this t y student point
	 */
	public TYStudentPointPK getPrimaryKey();

	/**
	 * Sets the primary key of this t y student point
	 *
	 * @param pk the primary key of this t y student point
	 */
	public void setPrimaryKey(TYStudentPointPK pk);

	/**
	 * Gets the courses of this t y student point.
	 *
	 * @return the courses of this t y student point
	 */
	public int getCourses();

	/**
	 * Sets the courses of this t y student point.
	 *
	 * @param courses the courses of this t y student point
	 */
	public void setCourses(int courses);

	/**
	 * Gets the semester of this t y student point.
	 *
	 * @return the semester of this t y student point
	 */
	public int getSemester();

	/**
	 * Sets the semester of this t y student point.
	 *
	 * @param semester the semester of this t y student point
	 */
	public void setSemester(int semester);

	/**
	 * Gets the student id of this t y student point.
	 *
	 * @return the student id of this t y student point
	 */
	public long getStudentId();

	/**
	 * Sets the student id of this t y student point.
	 *
	 * @param studentId the student id of this t y student point
	 */
	public void setStudentId(long studentId);

	/**
	 * Gets the subject id of this t y student point.
	 *
	 * @return the subject id of this t y student point
	 */
	public long getSubjectId();

	/**
	 * Sets the subject id of this t y student point.
	 *
	 * @param subjectId the subject id of this t y student point
	 */
	public void setSubjectId(long subjectId);

	/**
	 * Gets the point type of this t y student point.
	 *
	 * @return the point type of this t y student point
	 */
	public int getPointType();

	/**
	 * Sets the point type of this t y student point.
	 *
	 * @param pointType the point type of this t y student point
	 */
	public void setPointType(int pointType);

	/**
	 * Gets the point index of this t y student point.
	 *
	 * @return the point index of this t y student point
	 */
	public int getPointIndex();

	/**
	 * Sets the point index of this t y student point.
	 *
	 * @param pointIndex the point index of this t y student point
	 */
	public void setPointIndex(int pointIndex);

	/**
	 * Gets the point factor of this t y student point.
	 *
	 * @return the point factor of this t y student point
	 */
	public int getPointFactor();

	/**
	 * Sets the point factor of this t y student point.
	 *
	 * @param pointFactor the point factor of this t y student point
	 */
	public void setPointFactor(int pointFactor);

	/**
	 * Gets the point of this t y student point.
	 *
	 * @return the point of this t y student point
	 */
	public double getPoint();

	/**
	 * Sets the point of this t y student point.
	 *
	 * @param point the point of this t y student point
	 */
	public void setPoint(double point);

	/**
	 * Gets the modified date of this t y student point.
	 *
	 * @return the modified date of this t y student point
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this t y student point.
	 *
	 * @param modifiedDate the modified date of this t y student point
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Gets the user id of this t y student point.
	 *
	 * @return the user id of this t y student point
	 */
	public long getUserId();

	/**
	 * Sets the user id of this t y student point.
	 *
	 * @param userId the user id of this t y student point
	 */
	public void setUserId(long userId);

	/**
	 * Gets the user uuid of this t y student point.
	 *
	 * @return the user uuid of this t y student point
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this t y student point.
	 *
	 * @param userUuid the user uuid of this t y student point
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Gets a copy of this t y student point as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public TYStudentPoint toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(TYStudentPoint tyStudentPoint);

	public int hashCode();

	public String toString();

	public String toXmlString();
}