/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.tvd.thptty.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the TYSubject service. Represents a row in the &quot;TY_TYSubject&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.tvd.thptty.model.impl.TYSubjectModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.tvd.thptty.model.impl.TYSubjectImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a t y subject model instance should use the {@link TYSubject} interface instead.
 * </p>
 *
 * @author Ta Van Dung
 * @see TYSubject
 * @see org.tvd.thptty.model.impl.TYSubjectImpl
 * @see org.tvd.thptty.model.impl.TYSubjectModelImpl
 * @generated
 */
public interface TYSubjectModel extends BaseModel<TYSubject> {
	/**
	 * Gets the primary key of this t y subject.
	 *
	 * @return the primary key of this t y subject
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this t y subject
	 *
	 * @param pk the primary key of this t y subject
	 */
	public void setPrimaryKey(long pk);

	/**
	 * Gets the subject id of this t y subject.
	 *
	 * @return the subject id of this t y subject
	 */
	public long getSubjectId();

	/**
	 * Sets the subject id of this t y subject.
	 *
	 * @param subjectId the subject id of this t y subject
	 */
	public void setSubjectId(long subjectId);

	/**
	 * Gets the company id of this t y subject.
	 *
	 * @return the company id of this t y subject
	 */
	public long getCompanyId();

	/**
	 * Sets the company id of this t y subject.
	 *
	 * @param companyId the company id of this t y subject
	 */
	public void setCompanyId(long companyId);

	/**
	 * Gets the group id of this t y subject.
	 *
	 * @return the group id of this t y subject
	 */
	public long getGroupId();

	/**
	 * Sets the group id of this t y subject.
	 *
	 * @param groupId the group id of this t y subject
	 */
	public void setGroupId(long groupId);

	/**
	 * Gets the subject code of this t y subject.
	 *
	 * @return the subject code of this t y subject
	 */
	@AutoEscape
	public String getSubjectCode();

	/**
	 * Sets the subject code of this t y subject.
	 *
	 * @param subjectCode the subject code of this t y subject
	 */
	public void setSubjectCode(String subjectCode);

	/**
	 * Gets the subject name of this t y subject.
	 *
	 * @return the subject name of this t y subject
	 */
	@AutoEscape
	public String getSubjectName();

	/**
	 * Sets the subject name of this t y subject.
	 *
	 * @param subjectName the subject name of this t y subject
	 */
	public void setSubjectName(String subjectName);

	/**
	 * Gets the description of this t y subject.
	 *
	 * @return the description of this t y subject
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this t y subject.
	 *
	 * @param description the description of this t y subject
	 */
	public void setDescription(String description);

	/**
	 * Gets a copy of this t y subject as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public TYSubject toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(TYSubject tySubject);

	public int hashCode();

	public String toString();

	public String toXmlString();
}