/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.tvd.thptty.model;

import com.liferay.portal.kernel.annotation.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

/**
 * The base model interface for the TYTeacher service. Represents a row in the &quot;TY_TYTeacher&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link org.tvd.thptty.model.impl.TYTeacherModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link org.tvd.thptty.model.impl.TYTeacherImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this interface directly. All methods that expect a t y teacher model instance should use the {@link TYTeacher} interface instead.
 * </p>
 *
 * @author Ta Van Dung
 * @see TYTeacher
 * @see org.tvd.thptty.model.impl.TYTeacherImpl
 * @see org.tvd.thptty.model.impl.TYTeacherModelImpl
 * @generated
 */
public interface TYTeacherModel extends BaseModel<TYTeacher> {
	/**
	 * Gets the primary key of this t y teacher.
	 *
	 * @return the primary key of this t y teacher
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this t y teacher
	 *
	 * @param pk the primary key of this t y teacher
	 */
	public void setPrimaryKey(long pk);

	/**
	 * Gets the teacher id of this t y teacher.
	 *
	 * @return the teacher id of this t y teacher
	 */
	public long getTeacherId();

	/**
	 * Sets the teacher id of this t y teacher.
	 *
	 * @param teacherId the teacher id of this t y teacher
	 */
	public void setTeacherId(long teacherId);

	/**
	 * Gets the teacher degree of this t y teacher.
	 *
	 * @return the teacher degree of this t y teacher
	 */
	@AutoEscape
	public String getTeacherDegree();

	/**
	 * Sets the teacher degree of this t y teacher.
	 *
	 * @param teacherDegree the teacher degree of this t y teacher
	 */
	public void setTeacherDegree(String teacherDegree);

	/**
	 * Gets the teacher certificate of this t y teacher.
	 *
	 * @return the teacher certificate of this t y teacher
	 */
	@AutoEscape
	public String getTeacherCertificate();

	/**
	 * Sets the teacher certificate of this t y teacher.
	 *
	 * @param teacherCertificate the teacher certificate of this t y teacher
	 */
	public void setTeacherCertificate(String teacherCertificate);

	/**
	 * Gets the user id of this t y teacher.
	 *
	 * @return the user id of this t y teacher
	 */
	public long getUserId();

	/**
	 * Sets the user id of this t y teacher.
	 *
	 * @param userId the user id of this t y teacher
	 */
	public void setUserId(long userId);

	/**
	 * Gets the user uuid of this t y teacher.
	 *
	 * @return the user uuid of this t y teacher
	 * @throws SystemException if a system exception occurred
	 */
	public String getUserUuid() throws SystemException;

	/**
	 * Sets the user uuid of this t y teacher.
	 *
	 * @param userUuid the user uuid of this t y teacher
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Gets a copy of this t y teacher as an escaped model instance by wrapping it with an {@link com.liferay.portal.kernel.bean.AutoEscapeBeanHandler}.
	 *
	 * @return the escaped model instance
	 * @see com.liferay.portal.kernel.bean.AutoEscapeBeanHandler
	 */
	public TYTeacher toEscapedModel();

	public boolean isNew();

	public void setNew(boolean n);

	public boolean isCachedModel();

	public void setCachedModel(boolean cachedModel);

	public boolean isEscapedModel();

	public void setEscapedModel(boolean escapedModel);

	public Serializable getPrimaryKeyObj();

	public ExpandoBridge getExpandoBridge();

	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	public Object clone();

	public int compareTo(TYTeacher tyTeacher);

	public int hashCode();

	public String toString();

	public String toXmlString();
}