/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.ms.internet.message.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.util.PortalUtil;

import com.ms.internet.message.model.MSMSender;
import com.ms.internet.message.model.MSMSenderModel;
import com.ms.internet.message.service.persistence.MSMSenderPK;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

import java.util.Date;

/**
 * The base model implementation for the MSMSender service. Represents a row in the &quot;MS_MSMSender&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link com.ms.internet.message.model.MSMSenderModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link MSMSenderImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. All methods that expect a m s m sender model instance should use the {@link com.ms.internet.message.model.MSMSender} interface instead.
 * </p>
 *
 * @author I Am Dung
 * @see MSMSenderImpl
 * @see com.ms.internet.message.model.MSMSender
 * @see com.ms.internet.message.model.MSMSenderModel
 * @generated
 */
public class MSMSenderModelImpl extends BaseModelImpl<MSMSender>
	implements MSMSenderModel {
	public static final String TABLE_NAME = "MS_MSMSender";
	public static final Object[][] TABLE_COLUMNS = {
			{ "userId", new Integer(Types.BIGINT) },
			{ "messageId", new Integer(Types.BIGINT) },
			{ "dateSend", new Integer(Types.TIMESTAMP) }
		};
	public static final String TABLE_SQL_CREATE = "create table MS_MSMSender (userId LONG not null,messageId LONG not null,dateSend DATE null,primary key (userId, messageId))";
	public static final String TABLE_SQL_DROP = "drop table MS_MSMSender";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.com.ms.internet.message.model.MSMSender"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.com.ms.internet.message.model.MSMSender"),
			true);
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.com.ms.internet.message.model.MSMSender"));

	public MSMSenderModelImpl() {
	}

	public MSMSenderPK getPrimaryKey() {
		return new MSMSenderPK(_userId, _messageId);
	}

	public void setPrimaryKey(MSMSenderPK pk) {
		setUserId(pk.userId);
		setMessageId(pk.messageId);
	}

	public Serializable getPrimaryKeyObj() {
		return new MSMSenderPK(_userId, _messageId);
	}

	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public long getMessageId() {
		return _messageId;
	}

	public void setMessageId(long messageId) {
		if (!_setOriginalMessageId) {
			_setOriginalMessageId = true;

			_originalMessageId = _messageId;
		}

		_messageId = messageId;
	}

	public long getOriginalMessageId() {
		return _originalMessageId;
	}

	public Date getDateSend() {
		return _dateSend;
	}

	public void setDateSend(Date dateSend) {
		_dateSend = dateSend;
	}

	public MSMSender toEscapedModel() {
		if (isEscapedModel()) {
			return (MSMSender)this;
		}
		else {
			return (MSMSender)Proxy.newProxyInstance(MSMSender.class.getClassLoader(),
				new Class[] { MSMSender.class }, new AutoEscapeBeanHandler(this));
		}
	}

	public Object clone() {
		MSMSenderImpl msmSenderImpl = new MSMSenderImpl();

		msmSenderImpl.setUserId(getUserId());

		msmSenderImpl.setMessageId(getMessageId());

		MSMSenderModelImpl msmSenderModelImpl = msmSenderImpl;

		msmSenderModelImpl._originalMessageId = msmSenderModelImpl._messageId;

		msmSenderModelImpl._setOriginalMessageId = false;
		msmSenderImpl.setDateSend(getDateSend());

		return msmSenderImpl;
	}

	public int compareTo(MSMSender msmSender) {
		MSMSenderPK pk = msmSender.getPrimaryKey();

		return getPrimaryKey().compareTo(pk);
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		MSMSender msmSender = null;

		try {
			msmSender = (MSMSender)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		MSMSenderPK pk = msmSender.getPrimaryKey();

		if (getPrimaryKey().equals(pk)) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	public String toString() {
		StringBundler sb = new StringBundler(7);

		sb.append("{userId=");
		sb.append(getUserId());
		sb.append(", messageId=");
		sb.append(getMessageId());
		sb.append(", dateSend=");
		sb.append(getDateSend());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(13);

		sb.append("<model><model-name>");
		sb.append("com.ms.internet.message.model.MSMSender");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>messageId</column-name><column-value><![CDATA[");
		sb.append(getMessageId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>dateSend</column-name><column-value><![CDATA[");
		sb.append(getDateSend());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private long _userId;
	private String _userUuid;
	private long _messageId;
	private long _originalMessageId;
	private boolean _setOriginalMessageId;
	private Date _dateSend;
}