/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.tvd.thptty.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.kernel.util.StringPool;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.service.ServiceContext;
import com.liferay.portal.util.PortalUtil;

import com.liferay.portlet.expando.model.ExpandoBridge;
import com.liferay.portlet.expando.util.ExpandoBridgeFactoryUtil;

import org.tvd.thptty.model.TYClass;
import org.tvd.thptty.model.TYClassModel;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

import java.util.Date;

/**
 * The base model implementation for the TYClass service. Represents a row in the &quot;TY_TYClass&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.tvd.thptty.model.TYClassModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TYClassImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. All methods that expect a t y class model instance should use the {@link org.tvd.thptty.model.TYClass} interface instead.
 * </p>
 *
 * @author Ta Van Dung
 * @see TYClassImpl
 * @see org.tvd.thptty.model.TYClass
 * @see org.tvd.thptty.model.TYClassModel
 * @generated
 */
public class TYClassModelImpl extends BaseModelImpl<TYClass>
	implements TYClassModel {
	public static final String TABLE_NAME = "TY_TYClass";
	public static final Object[][] TABLE_COLUMNS = {
			{ "classId", new Integer(Types.BIGINT) },
			{ "companyId", new Integer(Types.BIGINT) },
			{ "groupId", new Integer(Types.BIGINT) },
			{ "classCode", new Integer(Types.VARCHAR) },
			{ "classGroup", new Integer(Types.INTEGER) },
			{ "className", new Integer(Types.VARCHAR) },
			{ "modifiedDate", new Integer(Types.TIMESTAMP) },
			{ "userId", new Integer(Types.BIGINT) }
		};
	public static final String TABLE_SQL_CREATE = "create table TY_TYClass (classId LONG not null primary key,companyId LONG,groupId LONG,classCode VARCHAR(75) null,classGroup INTEGER,className VARCHAR(75) null,modifiedDate DATE null,userId LONG)";
	public static final String TABLE_SQL_DROP = "drop table TY_TYClass";
	public static final String ORDER_BY_JPQL = " ORDER BY tyClass.classId ASC";
	public static final String ORDER_BY_SQL = " ORDER BY TY_TYClass.classId ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.tvd.thptty.model.TYClass"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.tvd.thptty.model.TYClass"),
			true);
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.tvd.thptty.model.TYClass"));

	public TYClassModelImpl() {
	}

	public long getPrimaryKey() {
		return _classId;
	}

	public void setPrimaryKey(long pk) {
		setClassId(pk);
	}

	public Serializable getPrimaryKeyObj() {
		return new Long(_classId);
	}

	public long getClassId() {
		return _classId;
	}

	public void setClassId(long classId) {
		if (!_setOriginalClassId) {
			_setOriginalClassId = true;

			_originalClassId = _classId;
		}

		_classId = classId;
	}

	public long getOriginalClassId() {
		return _originalClassId;
	}

	public long getCompanyId() {
		return _companyId;
	}

	public void setCompanyId(long companyId) {
		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	public long getGroupId() {
		return _groupId;
	}

	public void setGroupId(long groupId) {
		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	public String getClassCode() {
		if (_classCode == null) {
			return StringPool.BLANK;
		}
		else {
			return _classCode;
		}
	}

	public void setClassCode(String classCode) {
		_classCode = classCode;
	}

	public int getClassGroup() {
		return _classGroup;
	}

	public void setClassGroup(int classGroup) {
		if (!_setOriginalClassGroup) {
			_setOriginalClassGroup = true;

			_originalClassGroup = _classGroup;
		}

		_classGroup = classGroup;
	}

	public int getOriginalClassGroup() {
		return _originalClassGroup;
	}

	public String getClassName() {
		if (_className == null) {
			return StringPool.BLANK;
		}
		else {
			return _className;
		}
	}

	public void setClassName(String className) {
		if (_originalClassName == null) {
			_originalClassName = _className;
		}

		_className = className;
	}

	public String getOriginalClassName() {
		return GetterUtil.getString(_originalClassName);
	}

	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public void setModifiedDate(Date modifiedDate) {
		_modifiedDate = modifiedDate;
	}

	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public TYClass toEscapedModel() {
		if (isEscapedModel()) {
			return (TYClass)this;
		}
		else {
			return (TYClass)Proxy.newProxyInstance(TYClass.class.getClassLoader(),
				new Class[] { TYClass.class }, new AutoEscapeBeanHandler(this));
		}
	}

	public ExpandoBridge getExpandoBridge() {
		if (_expandoBridge == null) {
			_expandoBridge = ExpandoBridgeFactoryUtil.getExpandoBridge(getCompanyId(),
					TYClass.class.getName(), getPrimaryKey());
		}

		return _expandoBridge;
	}

	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		getExpandoBridge().setAttributes(serviceContext);
	}

	public Object clone() {
		TYClassImpl tyClassImpl = new TYClassImpl();

		tyClassImpl.setClassId(getClassId());

		TYClassModelImpl tyClassModelImpl = tyClassImpl;

		tyClassModelImpl._originalClassId = tyClassModelImpl._classId;

		tyClassModelImpl._setOriginalClassId = false;
		tyClassImpl.setCompanyId(getCompanyId());

		tyClassModelImpl._originalCompanyId = tyClassModelImpl._companyId;

		tyClassModelImpl._setOriginalCompanyId = false;
		tyClassImpl.setGroupId(getGroupId());

		tyClassModelImpl._originalGroupId = tyClassModelImpl._groupId;

		tyClassModelImpl._setOriginalGroupId = false;
		tyClassImpl.setClassCode(getClassCode());

		tyClassImpl.setClassGroup(getClassGroup());

		tyClassModelImpl._originalClassGroup = tyClassModelImpl._classGroup;

		tyClassModelImpl._setOriginalClassGroup = false;
		tyClassImpl.setClassName(getClassName());

		tyClassModelImpl._originalClassName = tyClassModelImpl._className;

		tyClassImpl.setModifiedDate(getModifiedDate());

		tyClassImpl.setUserId(getUserId());

		return tyClassImpl;
	}

	public int compareTo(TYClass tyClass) {
		int value = 0;

		if (getClassId() < tyClass.getClassId()) {
			value = -1;
		}
		else if (getClassId() > tyClass.getClassId()) {
			value = 1;
		}
		else {
			value = 0;
		}

		if (value != 0) {
			return value;
		}

		return 0;
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		TYClass tyClass = null;

		try {
			tyClass = (TYClass)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		long pk = tyClass.getPrimaryKey();

		if (getPrimaryKey() == pk) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return (int)getPrimaryKey();
	}

	public String toString() {
		StringBundler sb = new StringBundler(17);

		sb.append("{classId=");
		sb.append(getClassId());
		sb.append(", companyId=");
		sb.append(getCompanyId());
		sb.append(", groupId=");
		sb.append(getGroupId());
		sb.append(", classCode=");
		sb.append(getClassCode());
		sb.append(", classGroup=");
		sb.append(getClassGroup());
		sb.append(", className=");
		sb.append(getClassName());
		sb.append(", modifiedDate=");
		sb.append(getModifiedDate());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(28);

		sb.append("<model><model-name>");
		sb.append("org.tvd.thptty.model.TYClass");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>classId</column-name><column-value><![CDATA[");
		sb.append(getClassId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>companyId</column-name><column-value><![CDATA[");
		sb.append(getCompanyId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>groupId</column-name><column-value><![CDATA[");
		sb.append(getGroupId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>classCode</column-name><column-value><![CDATA[");
		sb.append(getClassCode());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>classGroup</column-name><column-value><![CDATA[");
		sb.append(getClassGroup());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>className</column-name><column-value><![CDATA[");
		sb.append(getClassName());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>modifiedDate</column-name><column-value><![CDATA[");
		sb.append(getModifiedDate());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private long _classId;
	private long _originalClassId;
	private boolean _setOriginalClassId;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private String _classCode;
	private int _classGroup;
	private int _originalClassGroup;
	private boolean _setOriginalClassGroup;
	private String _className;
	private String _originalClassName;
	private Date _modifiedDate;
	private long _userId;
	private String _userUuid;
	private transient ExpandoBridge _expandoBridge;
}