/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.tvd.thptty.model.impl;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.StringBundler;
import com.liferay.portal.model.impl.BaseModelImpl;
import com.liferay.portal.util.PortalUtil;

import org.tvd.thptty.model.TYSubjectClassUserRole;
import org.tvd.thptty.model.TYSubjectClassUserRoleModel;
import org.tvd.thptty.service.persistence.TYSubjectClassUserRolePK;

import java.io.Serializable;

import java.lang.reflect.Proxy;

import java.sql.Types;

/**
 * The base model implementation for the TYSubjectClassUserRole service. Represents a row in the &quot;TY_TYSubjectClassUserRole&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link org.tvd.thptty.model.TYSubjectClassUserRoleModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link TYSubjectClassUserRoleImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. All methods that expect a t y subject class user role model instance should use the {@link org.tvd.thptty.model.TYSubjectClassUserRole} interface instead.
 * </p>
 *
 * @author Ta Van Dung
 * @see TYSubjectClassUserRoleImpl
 * @see org.tvd.thptty.model.TYSubjectClassUserRole
 * @see org.tvd.thptty.model.TYSubjectClassUserRoleModel
 * @generated
 */
public class TYSubjectClassUserRoleModelImpl extends BaseModelImpl<TYSubjectClassUserRole>
	implements TYSubjectClassUserRoleModel {
	public static final String TABLE_NAME = "TY_TYSubjectClassUserRole";
	public static final Object[][] TABLE_COLUMNS = {
			{ "courses", new Integer(Types.INTEGER) },
			{ "subjectId", new Integer(Types.BIGINT) },
			{ "classId", new Integer(Types.BIGINT) },
			{ "userId", new Integer(Types.BIGINT) },
			{ "roleId", new Integer(Types.BIGINT) },
			{ "status", new Integer(Types.INTEGER) }
		};
	public static final String TABLE_SQL_CREATE = "create table TY_TYSubjectClassUserRole (courses INTEGER not null,subjectId LONG not null,classId LONG not null,userId LONG not null,roleId LONG not null,status INTEGER,primary key (courses, subjectId, classId, userId, roleId))";
	public static final String TABLE_SQL_DROP = "drop table TY_TYSubjectClassUserRole";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.entity.cache.enabled.org.tvd.thptty.model.TYSubjectClassUserRole"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(com.liferay.util.service.ServiceProps.get(
				"value.object.finder.cache.enabled.org.tvd.thptty.model.TYSubjectClassUserRole"),
			true);
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(com.liferay.util.service.ServiceProps.get(
				"lock.expiration.time.org.tvd.thptty.model.TYSubjectClassUserRole"));

	public TYSubjectClassUserRoleModelImpl() {
	}

	public TYSubjectClassUserRolePK getPrimaryKey() {
		return new TYSubjectClassUserRolePK(_courses, _subjectId, _classId,
			_userId, _roleId);
	}

	public void setPrimaryKey(TYSubjectClassUserRolePK pk) {
		setCourses(pk.courses);
		setSubjectId(pk.subjectId);
		setClassId(pk.classId);
		setUserId(pk.userId);
		setRoleId(pk.roleId);
	}

	public Serializable getPrimaryKeyObj() {
		return new TYSubjectClassUserRolePK(_courses, _subjectId, _classId,
			_userId, _roleId);
	}

	public int getCourses() {
		return _courses;
	}

	public void setCourses(int courses) {
		_courses = courses;
	}

	public long getSubjectId() {
		return _subjectId;
	}

	public void setSubjectId(long subjectId) {
		_subjectId = subjectId;
	}

	public long getClassId() {
		return _classId;
	}

	public void setClassId(long classId) {
		_classId = classId;
	}

	public long getUserId() {
		return _userId;
	}

	public void setUserId(long userId) {
		_userId = userId;
	}

	public String getUserUuid() throws SystemException {
		return PortalUtil.getUserValue(getUserId(), "uuid", _userUuid);
	}

	public void setUserUuid(String userUuid) {
		_userUuid = userUuid;
	}

	public long getRoleId() {
		return _roleId;
	}

	public void setRoleId(long roleId) {
		_roleId = roleId;
	}

	public int getStatus() {
		return _status;
	}

	public void setStatus(int status) {
		_status = status;
	}

	public TYSubjectClassUserRole toEscapedModel() {
		if (isEscapedModel()) {
			return (TYSubjectClassUserRole)this;
		}
		else {
			return (TYSubjectClassUserRole)Proxy.newProxyInstance(TYSubjectClassUserRole.class.getClassLoader(),
				new Class[] { TYSubjectClassUserRole.class },
				new AutoEscapeBeanHandler(this));
		}
	}

	public Object clone() {
		TYSubjectClassUserRoleImpl tySubjectClassUserRoleImpl = new TYSubjectClassUserRoleImpl();

		tySubjectClassUserRoleImpl.setCourses(getCourses());

		tySubjectClassUserRoleImpl.setSubjectId(getSubjectId());

		tySubjectClassUserRoleImpl.setClassId(getClassId());

		tySubjectClassUserRoleImpl.setUserId(getUserId());

		tySubjectClassUserRoleImpl.setRoleId(getRoleId());

		tySubjectClassUserRoleImpl.setStatus(getStatus());

		return tySubjectClassUserRoleImpl;
	}

	public int compareTo(TYSubjectClassUserRole tySubjectClassUserRole) {
		TYSubjectClassUserRolePK pk = tySubjectClassUserRole.getPrimaryKey();

		return getPrimaryKey().compareTo(pk);
	}

	public boolean equals(Object obj) {
		if (obj == null) {
			return false;
		}

		TYSubjectClassUserRole tySubjectClassUserRole = null;

		try {
			tySubjectClassUserRole = (TYSubjectClassUserRole)obj;
		}
		catch (ClassCastException cce) {
			return false;
		}

		TYSubjectClassUserRolePK pk = tySubjectClassUserRole.getPrimaryKey();

		if (getPrimaryKey().equals(pk)) {
			return true;
		}
		else {
			return false;
		}
	}

	public int hashCode() {
		return getPrimaryKey().hashCode();
	}

	public String toString() {
		StringBundler sb = new StringBundler(13);

		sb.append("{courses=");
		sb.append(getCourses());
		sb.append(", subjectId=");
		sb.append(getSubjectId());
		sb.append(", classId=");
		sb.append(getClassId());
		sb.append(", userId=");
		sb.append(getUserId());
		sb.append(", roleId=");
		sb.append(getRoleId());
		sb.append(", status=");
		sb.append(getStatus());
		sb.append("}");

		return sb.toString();
	}

	public String toXmlString() {
		StringBundler sb = new StringBundler(22);

		sb.append("<model><model-name>");
		sb.append("org.tvd.thptty.model.TYSubjectClassUserRole");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>courses</column-name><column-value><![CDATA[");
		sb.append(getCourses());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>subjectId</column-name><column-value><![CDATA[");
		sb.append(getSubjectId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>classId</column-name><column-value><![CDATA[");
		sb.append(getClassId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>userId</column-name><column-value><![CDATA[");
		sb.append(getUserId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>roleId</column-name><column-value><![CDATA[");
		sb.append(getRoleId());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>status</column-name><column-value><![CDATA[");
		sb.append(getStatus());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private int _courses;
	private long _subjectId;
	private long _classId;
	private long _userId;
	private String _userUuid;
	private long _roleId;
	private int _status;
}