/**
 * Copyright (c) 2000-2011 Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package org.tvd.thptty.service.base;

import com.liferay.counter.service.CounterLocalService;

import com.liferay.portal.kernel.annotation.BeanReference;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.service.ResourceLocalService;
import com.liferay.portal.service.ResourceService;
import com.liferay.portal.service.UserLocalService;
import com.liferay.portal.service.UserService;
import com.liferay.portal.service.persistence.ResourcePersistence;
import com.liferay.portal.service.persistence.UserPersistence;

import org.tvd.thptty.model.TYStudentPointReserve;
import org.tvd.thptty.service.SemesterLocalService;
import org.tvd.thptty.service.TYClassLocalService;
import org.tvd.thptty.service.TYClassStudentLocalService;
import org.tvd.thptty.service.TYClassUserRoleLocalService;
import org.tvd.thptty.service.TYMessagesLocalService;
import org.tvd.thptty.service.TYPrioritySubjectLocalService;
import org.tvd.thptty.service.TYStudentConductLocalService;
import org.tvd.thptty.service.TYStudentLocalService;
import org.tvd.thptty.service.TYStudentPointLocalService;
import org.tvd.thptty.service.TYStudentPointReserveLocalService;
import org.tvd.thptty.service.TYSubjectClassUserRoleLocalService;
import org.tvd.thptty.service.TYSubjectLocalService;
import org.tvd.thptty.service.TYSubjectUserRoleLocalService;
import org.tvd.thptty.service.TYTeacherLocalService;
import org.tvd.thptty.service.persistence.SemesterPersistence;
import org.tvd.thptty.service.persistence.TYClassPersistence;
import org.tvd.thptty.service.persistence.TYClassStudentPersistence;
import org.tvd.thptty.service.persistence.TYClassUserRolePersistence;
import org.tvd.thptty.service.persistence.TYMessagesPersistence;
import org.tvd.thptty.service.persistence.TYPrioritySubjectPersistence;
import org.tvd.thptty.service.persistence.TYStudentConductPersistence;
import org.tvd.thptty.service.persistence.TYStudentPersistence;
import org.tvd.thptty.service.persistence.TYStudentPointFinder;
import org.tvd.thptty.service.persistence.TYStudentPointPersistence;
import org.tvd.thptty.service.persistence.TYStudentPointReservePK;
import org.tvd.thptty.service.persistence.TYStudentPointReservePersistence;
import org.tvd.thptty.service.persistence.TYSubjectClassUserRolePersistence;
import org.tvd.thptty.service.persistence.TYSubjectPersistence;
import org.tvd.thptty.service.persistence.TYSubjectUserRolePersistence;
import org.tvd.thptty.service.persistence.TYTeacherPersistence;

import java.util.List;

import javax.sql.DataSource;

/**
 * The base implementation of the t y student point reserve local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link org.tvd.thptty.service.impl.TYStudentPointReserveLocalServiceImpl}.
 * </p>
 *
 * <p>
 * Never modify or reference this class directly. Always use {@link org.tvd.thptty.service.TYStudentPointReserveLocalServiceUtil} to access the t y student point reserve local service.
 * </p>
 *
 * @author Ta Van Dung
 * @see org.tvd.thptty.service.impl.TYStudentPointReserveLocalServiceImpl
 * @see org.tvd.thptty.service.TYStudentPointReserveLocalServiceUtil
 * @generated
 */
public abstract class TYStudentPointReserveLocalServiceBaseImpl
	implements TYStudentPointReserveLocalService {
	/**
	 * Adds the t y student point reserve to the database. Also notifies the appropriate model listeners.
	 *
	 * @param tyStudentPointReserve the t y student point reserve to add
	 * @return the t y student point reserve that was added
	 * @throws SystemException if a system exception occurred
	 */
	public TYStudentPointReserve addTYStudentPointReserve(
		TYStudentPointReserve tyStudentPointReserve) throws SystemException {
		tyStudentPointReserve.setNew(true);

		return tyStudentPointReservePersistence.update(tyStudentPointReserve,
			false);
	}

	/**
	 * Creates a new t y student point reserve with the primary key. Does not add the t y student point reserve to the database.
	 *
	 * @param tyStudentPointReservePK the primary key for the new t y student point reserve
	 * @return the new t y student point reserve
	 */
	public TYStudentPointReserve createTYStudentPointReserve(
		TYStudentPointReservePK tyStudentPointReservePK) {
		return tyStudentPointReservePersistence.create(tyStudentPointReservePK);
	}

	/**
	 * Deletes the t y student point reserve with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param tyStudentPointReservePK the primary key of the t y student point reserve to delete
	 * @throws PortalException if a t y student point reserve with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteTYStudentPointReserve(
		TYStudentPointReservePK tyStudentPointReservePK)
		throws PortalException, SystemException {
		tyStudentPointReservePersistence.remove(tyStudentPointReservePK);
	}

	/**
	 * Deletes the t y student point reserve from the database. Also notifies the appropriate model listeners.
	 *
	 * @param tyStudentPointReserve the t y student point reserve to delete
	 * @throws SystemException if a system exception occurred
	 */
	public void deleteTYStudentPointReserve(
		TYStudentPointReserve tyStudentPointReserve) throws SystemException {
		tyStudentPointReservePersistence.remove(tyStudentPointReserve);
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @return the matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery)
		throws SystemException {
		return tyStudentPointReservePersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @param start the lower bound of the range of model instances to return
	 * @param end the upper bound of the range of model instances to return (not inclusive)
	 * @return the range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end)
		throws SystemException {
		return tyStudentPointReservePersistence.findWithDynamicQuery(dynamicQuery,
			start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @param start the lower bound of the range of model instances to return
	 * @param end the upper bound of the range of model instances to return (not inclusive)
	 * @param orderByComparator the comparator to order the results by
	 * @return the ordered range of matching rows
	 * @throws SystemException if a system exception occurred
	 */
	@SuppressWarnings("rawtypes")
	public List dynamicQuery(DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator orderByComparator) throws SystemException {
		return tyStudentPointReservePersistence.findWithDynamicQuery(dynamicQuery,
			start, end, orderByComparator);
	}

	/**
	 * Counts the number of rows that match the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query to search with
	 * @return the number of rows that match the dynamic query
	 * @throws SystemException if a system exception occurred
	 */
	public long dynamicQueryCount(DynamicQuery dynamicQuery)
		throws SystemException {
		return tyStudentPointReservePersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Gets the t y student point reserve with the primary key.
	 *
	 * @param tyStudentPointReservePK the primary key of the t y student point reserve to get
	 * @return the t y student point reserve
	 * @throws PortalException if a t y student point reserve with the primary key could not be found
	 * @throws SystemException if a system exception occurred
	 */
	public TYStudentPointReserve getTYStudentPointReserve(
		TYStudentPointReservePK tyStudentPointReservePK)
		throws PortalException, SystemException {
		return tyStudentPointReservePersistence.findByPrimaryKey(tyStudentPointReservePK);
	}

	/**
	 * Gets a range of all the t y student point reserves.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to {@link com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS} will return the full result set.
	 * </p>
	 *
	 * @param start the lower bound of the range of t y student point reserves to return
	 * @param end the upper bound of the range of t y student point reserves to return (not inclusive)
	 * @return the range of t y student point reserves
	 * @throws SystemException if a system exception occurred
	 */
	public List<TYStudentPointReserve> getTYStudentPointReserves(int start,
		int end) throws SystemException {
		return tyStudentPointReservePersistence.findAll(start, end);
	}

	/**
	 * Gets the number of t y student point reserves.
	 *
	 * @return the number of t y student point reserves
	 * @throws SystemException if a system exception occurred
	 */
	public int getTYStudentPointReservesCount() throws SystemException {
		return tyStudentPointReservePersistence.countAll();
	}

	/**
	 * Updates the t y student point reserve in the database. Also notifies the appropriate model listeners.
	 *
	 * @param tyStudentPointReserve the t y student point reserve to update
	 * @return the t y student point reserve that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public TYStudentPointReserve updateTYStudentPointReserve(
		TYStudentPointReserve tyStudentPointReserve) throws SystemException {
		tyStudentPointReserve.setNew(false);

		return tyStudentPointReservePersistence.update(tyStudentPointReserve,
			true);
	}

	/**
	 * Updates the t y student point reserve in the database. Also notifies the appropriate model listeners.
	 *
	 * @param tyStudentPointReserve the t y student point reserve to update
	 * @param merge whether to merge the t y student point reserve with the current session. See {@link com.liferay.portal.service.persistence.BatchSession#update(com.liferay.portal.kernel.dao.orm.Session, com.liferay.portal.model.BaseModel, boolean)} for an explanation.
	 * @return the t y student point reserve that was updated
	 * @throws SystemException if a system exception occurred
	 */
	public TYStudentPointReserve updateTYStudentPointReserve(
		TYStudentPointReserve tyStudentPointReserve, boolean merge)
		throws SystemException {
		tyStudentPointReserve.setNew(false);

		return tyStudentPointReservePersistence.update(tyStudentPointReserve,
			merge);
	}

	/**
	 * Gets the t y class local service.
	 *
	 * @return the t y class local service
	 */
	public TYClassLocalService getTYClassLocalService() {
		return tyClassLocalService;
	}

	/**
	 * Sets the t y class local service.
	 *
	 * @param tyClassLocalService the t y class local service
	 */
	public void setTYClassLocalService(TYClassLocalService tyClassLocalService) {
		this.tyClassLocalService = tyClassLocalService;
	}

	/**
	 * Gets the t y class persistence.
	 *
	 * @return the t y class persistence
	 */
	public TYClassPersistence getTYClassPersistence() {
		return tyClassPersistence;
	}

	/**
	 * Sets the t y class persistence.
	 *
	 * @param tyClassPersistence the t y class persistence
	 */
	public void setTYClassPersistence(TYClassPersistence tyClassPersistence) {
		this.tyClassPersistence = tyClassPersistence;
	}

	/**
	 * Gets the t y student local service.
	 *
	 * @return the t y student local service
	 */
	public TYStudentLocalService getTYStudentLocalService() {
		return tyStudentLocalService;
	}

	/**
	 * Sets the t y student local service.
	 *
	 * @param tyStudentLocalService the t y student local service
	 */
	public void setTYStudentLocalService(
		TYStudentLocalService tyStudentLocalService) {
		this.tyStudentLocalService = tyStudentLocalService;
	}

	/**
	 * Gets the t y student persistence.
	 *
	 * @return the t y student persistence
	 */
	public TYStudentPersistence getTYStudentPersistence() {
		return tyStudentPersistence;
	}

	/**
	 * Sets the t y student persistence.
	 *
	 * @param tyStudentPersistence the t y student persistence
	 */
	public void setTYStudentPersistence(
		TYStudentPersistence tyStudentPersistence) {
		this.tyStudentPersistence = tyStudentPersistence;
	}

	/**
	 * Gets the t y class student local service.
	 *
	 * @return the t y class student local service
	 */
	public TYClassStudentLocalService getTYClassStudentLocalService() {
		return tyClassStudentLocalService;
	}

	/**
	 * Sets the t y class student local service.
	 *
	 * @param tyClassStudentLocalService the t y class student local service
	 */
	public void setTYClassStudentLocalService(
		TYClassStudentLocalService tyClassStudentLocalService) {
		this.tyClassStudentLocalService = tyClassStudentLocalService;
	}

	/**
	 * Gets the t y class student persistence.
	 *
	 * @return the t y class student persistence
	 */
	public TYClassStudentPersistence getTYClassStudentPersistence() {
		return tyClassStudentPersistence;
	}

	/**
	 * Sets the t y class student persistence.
	 *
	 * @param tyClassStudentPersistence the t y class student persistence
	 */
	public void setTYClassStudentPersistence(
		TYClassStudentPersistence tyClassStudentPersistence) {
		this.tyClassStudentPersistence = tyClassStudentPersistence;
	}

	/**
	 * Gets the t y class user role local service.
	 *
	 * @return the t y class user role local service
	 */
	public TYClassUserRoleLocalService getTYClassUserRoleLocalService() {
		return tyClassUserRoleLocalService;
	}

	/**
	 * Sets the t y class user role local service.
	 *
	 * @param tyClassUserRoleLocalService the t y class user role local service
	 */
	public void setTYClassUserRoleLocalService(
		TYClassUserRoleLocalService tyClassUserRoleLocalService) {
		this.tyClassUserRoleLocalService = tyClassUserRoleLocalService;
	}

	/**
	 * Gets the t y class user role persistence.
	 *
	 * @return the t y class user role persistence
	 */
	public TYClassUserRolePersistence getTYClassUserRolePersistence() {
		return tyClassUserRolePersistence;
	}

	/**
	 * Sets the t y class user role persistence.
	 *
	 * @param tyClassUserRolePersistence the t y class user role persistence
	 */
	public void setTYClassUserRolePersistence(
		TYClassUserRolePersistence tyClassUserRolePersistence) {
		this.tyClassUserRolePersistence = tyClassUserRolePersistence;
	}

	/**
	 * Gets the t y subject local service.
	 *
	 * @return the t y subject local service
	 */
	public TYSubjectLocalService getTYSubjectLocalService() {
		return tySubjectLocalService;
	}

	/**
	 * Sets the t y subject local service.
	 *
	 * @param tySubjectLocalService the t y subject local service
	 */
	public void setTYSubjectLocalService(
		TYSubjectLocalService tySubjectLocalService) {
		this.tySubjectLocalService = tySubjectLocalService;
	}

	/**
	 * Gets the t y subject persistence.
	 *
	 * @return the t y subject persistence
	 */
	public TYSubjectPersistence getTYSubjectPersistence() {
		return tySubjectPersistence;
	}

	/**
	 * Sets the t y subject persistence.
	 *
	 * @param tySubjectPersistence the t y subject persistence
	 */
	public void setTYSubjectPersistence(
		TYSubjectPersistence tySubjectPersistence) {
		this.tySubjectPersistence = tySubjectPersistence;
	}

	/**
	 * Gets the t y subject user role local service.
	 *
	 * @return the t y subject user role local service
	 */
	public TYSubjectUserRoleLocalService getTYSubjectUserRoleLocalService() {
		return tySubjectUserRoleLocalService;
	}

	/**
	 * Sets the t y subject user role local service.
	 *
	 * @param tySubjectUserRoleLocalService the t y subject user role local service
	 */
	public void setTYSubjectUserRoleLocalService(
		TYSubjectUserRoleLocalService tySubjectUserRoleLocalService) {
		this.tySubjectUserRoleLocalService = tySubjectUserRoleLocalService;
	}

	/**
	 * Gets the t y subject user role persistence.
	 *
	 * @return the t y subject user role persistence
	 */
	public TYSubjectUserRolePersistence getTYSubjectUserRolePersistence() {
		return tySubjectUserRolePersistence;
	}

	/**
	 * Sets the t y subject user role persistence.
	 *
	 * @param tySubjectUserRolePersistence the t y subject user role persistence
	 */
	public void setTYSubjectUserRolePersistence(
		TYSubjectUserRolePersistence tySubjectUserRolePersistence) {
		this.tySubjectUserRolePersistence = tySubjectUserRolePersistence;
	}

	/**
	 * Gets the t y teacher local service.
	 *
	 * @return the t y teacher local service
	 */
	public TYTeacherLocalService getTYTeacherLocalService() {
		return tyTeacherLocalService;
	}

	/**
	 * Sets the t y teacher local service.
	 *
	 * @param tyTeacherLocalService the t y teacher local service
	 */
	public void setTYTeacherLocalService(
		TYTeacherLocalService tyTeacherLocalService) {
		this.tyTeacherLocalService = tyTeacherLocalService;
	}

	/**
	 * Gets the t y teacher persistence.
	 *
	 * @return the t y teacher persistence
	 */
	public TYTeacherPersistence getTYTeacherPersistence() {
		return tyTeacherPersistence;
	}

	/**
	 * Sets the t y teacher persistence.
	 *
	 * @param tyTeacherPersistence the t y teacher persistence
	 */
	public void setTYTeacherPersistence(
		TYTeacherPersistence tyTeacherPersistence) {
		this.tyTeacherPersistence = tyTeacherPersistence;
	}

	/**
	 * Gets the t y student point reserve local service.
	 *
	 * @return the t y student point reserve local service
	 */
	public TYStudentPointReserveLocalService getTYStudentPointReserveLocalService() {
		return tyStudentPointReserveLocalService;
	}

	/**
	 * Sets the t y student point reserve local service.
	 *
	 * @param tyStudentPointReserveLocalService the t y student point reserve local service
	 */
	public void setTYStudentPointReserveLocalService(
		TYStudentPointReserveLocalService tyStudentPointReserveLocalService) {
		this.tyStudentPointReserveLocalService = tyStudentPointReserveLocalService;
	}

	/**
	 * Gets the t y student point reserve persistence.
	 *
	 * @return the t y student point reserve persistence
	 */
	public TYStudentPointReservePersistence getTYStudentPointReservePersistence() {
		return tyStudentPointReservePersistence;
	}

	/**
	 * Sets the t y student point reserve persistence.
	 *
	 * @param tyStudentPointReservePersistence the t y student point reserve persistence
	 */
	public void setTYStudentPointReservePersistence(
		TYStudentPointReservePersistence tyStudentPointReservePersistence) {
		this.tyStudentPointReservePersistence = tyStudentPointReservePersistence;
	}

	/**
	 * Gets the t y student point local service.
	 *
	 * @return the t y student point local service
	 */
	public TYStudentPointLocalService getTYStudentPointLocalService() {
		return tyStudentPointLocalService;
	}

	/**
	 * Sets the t y student point local service.
	 *
	 * @param tyStudentPointLocalService the t y student point local service
	 */
	public void setTYStudentPointLocalService(
		TYStudentPointLocalService tyStudentPointLocalService) {
		this.tyStudentPointLocalService = tyStudentPointLocalService;
	}

	/**
	 * Gets the t y student point persistence.
	 *
	 * @return the t y student point persistence
	 */
	public TYStudentPointPersistence getTYStudentPointPersistence() {
		return tyStudentPointPersistence;
	}

	/**
	 * Sets the t y student point persistence.
	 *
	 * @param tyStudentPointPersistence the t y student point persistence
	 */
	public void setTYStudentPointPersistence(
		TYStudentPointPersistence tyStudentPointPersistence) {
		this.tyStudentPointPersistence = tyStudentPointPersistence;
	}

	/**
	 * Gets the t y student point finder.
	 *
	 * @return the t y student point finder
	 */
	public TYStudentPointFinder getTYStudentPointFinder() {
		return tyStudentPointFinder;
	}

	/**
	 * Sets the t y student point finder.
	 *
	 * @param tyStudentPointFinder the t y student point finder
	 */
	public void setTYStudentPointFinder(
		TYStudentPointFinder tyStudentPointFinder) {
		this.tyStudentPointFinder = tyStudentPointFinder;
	}

	/**
	 * Gets the t y student conduct local service.
	 *
	 * @return the t y student conduct local service
	 */
	public TYStudentConductLocalService getTYStudentConductLocalService() {
		return tyStudentConductLocalService;
	}

	/**
	 * Sets the t y student conduct local service.
	 *
	 * @param tyStudentConductLocalService the t y student conduct local service
	 */
	public void setTYStudentConductLocalService(
		TYStudentConductLocalService tyStudentConductLocalService) {
		this.tyStudentConductLocalService = tyStudentConductLocalService;
	}

	/**
	 * Gets the t y student conduct persistence.
	 *
	 * @return the t y student conduct persistence
	 */
	public TYStudentConductPersistence getTYStudentConductPersistence() {
		return tyStudentConductPersistence;
	}

	/**
	 * Sets the t y student conduct persistence.
	 *
	 * @param tyStudentConductPersistence the t y student conduct persistence
	 */
	public void setTYStudentConductPersistence(
		TYStudentConductPersistence tyStudentConductPersistence) {
		this.tyStudentConductPersistence = tyStudentConductPersistence;
	}

	/**
	 * Gets the t y subject class user role local service.
	 *
	 * @return the t y subject class user role local service
	 */
	public TYSubjectClassUserRoleLocalService getTYSubjectClassUserRoleLocalService() {
		return tySubjectClassUserRoleLocalService;
	}

	/**
	 * Sets the t y subject class user role local service.
	 *
	 * @param tySubjectClassUserRoleLocalService the t y subject class user role local service
	 */
	public void setTYSubjectClassUserRoleLocalService(
		TYSubjectClassUserRoleLocalService tySubjectClassUserRoleLocalService) {
		this.tySubjectClassUserRoleLocalService = tySubjectClassUserRoleLocalService;
	}

	/**
	 * Gets the t y subject class user role persistence.
	 *
	 * @return the t y subject class user role persistence
	 */
	public TYSubjectClassUserRolePersistence getTYSubjectClassUserRolePersistence() {
		return tySubjectClassUserRolePersistence;
	}

	/**
	 * Sets the t y subject class user role persistence.
	 *
	 * @param tySubjectClassUserRolePersistence the t y subject class user role persistence
	 */
	public void setTYSubjectClassUserRolePersistence(
		TYSubjectClassUserRolePersistence tySubjectClassUserRolePersistence) {
		this.tySubjectClassUserRolePersistence = tySubjectClassUserRolePersistence;
	}

	/**
	 * Gets the t y priority subject local service.
	 *
	 * @return the t y priority subject local service
	 */
	public TYPrioritySubjectLocalService getTYPrioritySubjectLocalService() {
		return tyPrioritySubjectLocalService;
	}

	/**
	 * Sets the t y priority subject local service.
	 *
	 * @param tyPrioritySubjectLocalService the t y priority subject local service
	 */
	public void setTYPrioritySubjectLocalService(
		TYPrioritySubjectLocalService tyPrioritySubjectLocalService) {
		this.tyPrioritySubjectLocalService = tyPrioritySubjectLocalService;
	}

	/**
	 * Gets the t y priority subject persistence.
	 *
	 * @return the t y priority subject persistence
	 */
	public TYPrioritySubjectPersistence getTYPrioritySubjectPersistence() {
		return tyPrioritySubjectPersistence;
	}

	/**
	 * Sets the t y priority subject persistence.
	 *
	 * @param tyPrioritySubjectPersistence the t y priority subject persistence
	 */
	public void setTYPrioritySubjectPersistence(
		TYPrioritySubjectPersistence tyPrioritySubjectPersistence) {
		this.tyPrioritySubjectPersistence = tyPrioritySubjectPersistence;
	}

	/**
	 * Gets the semester local service.
	 *
	 * @return the semester local service
	 */
	public SemesterLocalService getSemesterLocalService() {
		return semesterLocalService;
	}

	/**
	 * Sets the semester local service.
	 *
	 * @param semesterLocalService the semester local service
	 */
	public void setSemesterLocalService(
		SemesterLocalService semesterLocalService) {
		this.semesterLocalService = semesterLocalService;
	}

	/**
	 * Gets the semester persistence.
	 *
	 * @return the semester persistence
	 */
	public SemesterPersistence getSemesterPersistence() {
		return semesterPersistence;
	}

	/**
	 * Sets the semester persistence.
	 *
	 * @param semesterPersistence the semester persistence
	 */
	public void setSemesterPersistence(SemesterPersistence semesterPersistence) {
		this.semesterPersistence = semesterPersistence;
	}

	/**
	 * Gets the t y messages local service.
	 *
	 * @return the t y messages local service
	 */
	public TYMessagesLocalService getTYMessagesLocalService() {
		return tyMessagesLocalService;
	}

	/**
	 * Sets the t y messages local service.
	 *
	 * @param tyMessagesLocalService the t y messages local service
	 */
	public void setTYMessagesLocalService(
		TYMessagesLocalService tyMessagesLocalService) {
		this.tyMessagesLocalService = tyMessagesLocalService;
	}

	/**
	 * Gets the t y messages persistence.
	 *
	 * @return the t y messages persistence
	 */
	public TYMessagesPersistence getTYMessagesPersistence() {
		return tyMessagesPersistence;
	}

	/**
	 * Sets the t y messages persistence.
	 *
	 * @param tyMessagesPersistence the t y messages persistence
	 */
	public void setTYMessagesPersistence(
		TYMessagesPersistence tyMessagesPersistence) {
		this.tyMessagesPersistence = tyMessagesPersistence;
	}

	/**
	 * Gets the counter local service.
	 *
	 * @return the counter local service
	 */
	public CounterLocalService getCounterLocalService() {
		return counterLocalService;
	}

	/**
	 * Sets the counter local service.
	 *
	 * @param counterLocalService the counter local service
	 */
	public void setCounterLocalService(CounterLocalService counterLocalService) {
		this.counterLocalService = counterLocalService;
	}

	/**
	 * Gets the resource local service.
	 *
	 * @return the resource local service
	 */
	public ResourceLocalService getResourceLocalService() {
		return resourceLocalService;
	}

	/**
	 * Sets the resource local service.
	 *
	 * @param resourceLocalService the resource local service
	 */
	public void setResourceLocalService(
		ResourceLocalService resourceLocalService) {
		this.resourceLocalService = resourceLocalService;
	}

	/**
	 * Gets the resource remote service.
	 *
	 * @return the resource remote service
	 */
	public ResourceService getResourceService() {
		return resourceService;
	}

	/**
	 * Sets the resource remote service.
	 *
	 * @param resourceService the resource remote service
	 */
	public void setResourceService(ResourceService resourceService) {
		this.resourceService = resourceService;
	}

	/**
	 * Gets the resource persistence.
	 *
	 * @return the resource persistence
	 */
	public ResourcePersistence getResourcePersistence() {
		return resourcePersistence;
	}

	/**
	 * Sets the resource persistence.
	 *
	 * @param resourcePersistence the resource persistence
	 */
	public void setResourcePersistence(ResourcePersistence resourcePersistence) {
		this.resourcePersistence = resourcePersistence;
	}

	/**
	 * Gets the user local service.
	 *
	 * @return the user local service
	 */
	public UserLocalService getUserLocalService() {
		return userLocalService;
	}

	/**
	 * Sets the user local service.
	 *
	 * @param userLocalService the user local service
	 */
	public void setUserLocalService(UserLocalService userLocalService) {
		this.userLocalService = userLocalService;
	}

	/**
	 * Gets the user remote service.
	 *
	 * @return the user remote service
	 */
	public UserService getUserService() {
		return userService;
	}

	/**
	 * Sets the user remote service.
	 *
	 * @param userService the user remote service
	 */
	public void setUserService(UserService userService) {
		this.userService = userService;
	}

	/**
	 * Gets the user persistence.
	 *
	 * @return the user persistence
	 */
	public UserPersistence getUserPersistence() {
		return userPersistence;
	}

	/**
	 * Sets the user persistence.
	 *
	 * @param userPersistence the user persistence
	 */
	public void setUserPersistence(UserPersistence userPersistence) {
		this.userPersistence = userPersistence;
	}

	/**
	 * Performs an SQL query.
	 *
	 * @param sql the sql query to perform
	 */
	protected void runSQL(String sql) throws SystemException {
		try {
			DataSource dataSource = tyStudentPointReservePersistence.getDataSource();

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(dataSource,
					sql, new int[0]);

			sqlUpdate.update();
		}
		catch (Exception e) {
			throw new SystemException(e);
		}
	}

	@BeanReference(type = TYClassLocalService.class)
	protected TYClassLocalService tyClassLocalService;
	@BeanReference(type = TYClassPersistence.class)
	protected TYClassPersistence tyClassPersistence;
	@BeanReference(type = TYStudentLocalService.class)
	protected TYStudentLocalService tyStudentLocalService;
	@BeanReference(type = TYStudentPersistence.class)
	protected TYStudentPersistence tyStudentPersistence;
	@BeanReference(type = TYClassStudentLocalService.class)
	protected TYClassStudentLocalService tyClassStudentLocalService;
	@BeanReference(type = TYClassStudentPersistence.class)
	protected TYClassStudentPersistence tyClassStudentPersistence;
	@BeanReference(type = TYClassUserRoleLocalService.class)
	protected TYClassUserRoleLocalService tyClassUserRoleLocalService;
	@BeanReference(type = TYClassUserRolePersistence.class)
	protected TYClassUserRolePersistence tyClassUserRolePersistence;
	@BeanReference(type = TYSubjectLocalService.class)
	protected TYSubjectLocalService tySubjectLocalService;
	@BeanReference(type = TYSubjectPersistence.class)
	protected TYSubjectPersistence tySubjectPersistence;
	@BeanReference(type = TYSubjectUserRoleLocalService.class)
	protected TYSubjectUserRoleLocalService tySubjectUserRoleLocalService;
	@BeanReference(type = TYSubjectUserRolePersistence.class)
	protected TYSubjectUserRolePersistence tySubjectUserRolePersistence;
	@BeanReference(type = TYTeacherLocalService.class)
	protected TYTeacherLocalService tyTeacherLocalService;
	@BeanReference(type = TYTeacherPersistence.class)
	protected TYTeacherPersistence tyTeacherPersistence;
	@BeanReference(type = TYStudentPointReserveLocalService.class)
	protected TYStudentPointReserveLocalService tyStudentPointReserveLocalService;
	@BeanReference(type = TYStudentPointReservePersistence.class)
	protected TYStudentPointReservePersistence tyStudentPointReservePersistence;
	@BeanReference(type = TYStudentPointLocalService.class)
	protected TYStudentPointLocalService tyStudentPointLocalService;
	@BeanReference(type = TYStudentPointPersistence.class)
	protected TYStudentPointPersistence tyStudentPointPersistence;
	@BeanReference(type = TYStudentPointFinder.class)
	protected TYStudentPointFinder tyStudentPointFinder;
	@BeanReference(type = TYStudentConductLocalService.class)
	protected TYStudentConductLocalService tyStudentConductLocalService;
	@BeanReference(type = TYStudentConductPersistence.class)
	protected TYStudentConductPersistence tyStudentConductPersistence;
	@BeanReference(type = TYSubjectClassUserRoleLocalService.class)
	protected TYSubjectClassUserRoleLocalService tySubjectClassUserRoleLocalService;
	@BeanReference(type = TYSubjectClassUserRolePersistence.class)
	protected TYSubjectClassUserRolePersistence tySubjectClassUserRolePersistence;
	@BeanReference(type = TYPrioritySubjectLocalService.class)
	protected TYPrioritySubjectLocalService tyPrioritySubjectLocalService;
	@BeanReference(type = TYPrioritySubjectPersistence.class)
	protected TYPrioritySubjectPersistence tyPrioritySubjectPersistence;
	@BeanReference(type = SemesterLocalService.class)
	protected SemesterLocalService semesterLocalService;
	@BeanReference(type = SemesterPersistence.class)
	protected SemesterPersistence semesterPersistence;
	@BeanReference(type = TYMessagesLocalService.class)
	protected TYMessagesLocalService tyMessagesLocalService;
	@BeanReference(type = TYMessagesPersistence.class)
	protected TYMessagesPersistence tyMessagesPersistence;
	@BeanReference(type = CounterLocalService.class)
	protected CounterLocalService counterLocalService;
	@BeanReference(type = ResourceLocalService.class)
	protected ResourceLocalService resourceLocalService;
	@BeanReference(type = ResourceService.class)
	protected ResourceService resourceService;
	@BeanReference(type = ResourcePersistence.class)
	protected ResourcePersistence resourcePersistence;
	@BeanReference(type = UserLocalService.class)
	protected UserLocalService userLocalService;
	@BeanReference(type = UserService.class)
	protected UserService userService;
	@BeanReference(type = UserPersistence.class)
	protected UserPersistence userPersistence;
}